### ISSUE TITLE
Cast bar "fill up" not smooth

### ISSUE THREAD

**Issue by Eric-Johnston** [shoestare/eCastingBarClassic#1]
Hey there, so when you're casting a spell and the bar is "filling up" it seems to do it in chunks, instead of it being smooth and fluid. Is this intended?

**Comment by Zwyk** [comment]
From what I tested it's only the Texture/StatusBar part that aren't smooth. The Spark has no issue.

**Comment by Zwyk** [comment]
Timestamps are stored in seconds instead of milliseconds which causes a precision issue.

I fixed it by changing the barStatusBar min and max values system to 0 to 1 (% progress) instead of timestamps (startTime to endTime) and adapting the rest to that. Might also work by keeping timestamps in milliseconds.

**Comment by InTrustABC** [comment]
Is that fix already pushed? I downloaded the newest Version and also have this problem.

**Comment by Zwyk** [comment]
I'm trying to contact the owner, I can't modify the files myself

**Comment by dutrieux** [comment]
@Zwyk You can maybe fork it and pull a request !

**Comment by shoestare** [comment]
@dutrieux I got in contact with Zwyk, @InTrustABC Zwyk's gonna be giving a helping hand and an update should be put out soon

**Comment by shoestare** [comment]
@Zwyk's code is added to the master branch now, cast bar lag is fixed.
